# Exporation of QC matrix for Geuvadis

Read in the matrix and re-assign levels of the operator (the center which performed sequencing).

```{r}
file <- "../qcstats/GD667.QCstats.txt"
library(readr)
qc <- read_delim(file,"\t")
library(rafalib)
means <- sapply(split(qc$GC_hist_bins_70, qc$Operator), mean)
o <- order(means)
qc$Operator <- factor(qc$Operator)
qc$Operator <- factor(qc$Operator, levels=levels(qc$Operator)[o])
lvls <- levels(qc$Operator)
levels(qc$Operator)[lvls == "MPIMG_S_DOKEL"] <- "MPIMG"
```


# this just to show who is missing high GC content reads

bigpar(3,3,mar=c(8,4,1,1))
for (i in 12:19) {
  boxplot(qc[[paste0("GC_hist_bins_",i*5)]] ~ qc$Operator,
          las=3)
  legend("topleft",legend=paste0("GC=",i*5),bty="n",pch=NA,cex=2)
}

colnames(qc)

library(RColorBrewer)

bigpar(1,1)
palette(c(brewer.pal(5, "Dark2"),brewer.pal(6, "Pastel1")))

with(qc, plot(GC_hist_bins_75, Operator,
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, LibraryConcentration_ng.ul,
              col=Operator, log="xy", pch=16))
with(qc, plot(GC_hist_bins_75, BioanalyzerSize_bp,
              col=Operator, log="x", pch=16))
with(qc, plot(GC_hist_bins_75, INSERT_SIZE_MODE,
              col=Operator, log="x", pch=16))

with(qc, plot(GC_hist_bins_75, RIN, col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, RNAConcentration_ng.ul,
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, RNAVolumeShipped_ul,
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, RNAQuantityShipped_ug,
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, LibraryQuantitySequencing_pM,
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75,
              12 * (as.numeric(substr(SequencingDate,2,3)) - 11) + 
              31 * as.numeric(substr(SequencingDate,4,5)) +
              as.numeric(substr(SequencingDate,6,7)),
              col=Operator, pch=16, ylab="days since 1/1/2011"))

with(qc, plot(GC_hist_bins_75, Total_read,
              col=Operator, log="x", pch=16))
with(qc, plot(GC_hist_bins_75, TOTAL_EXONIC_OVER_TOTAL_READS,
              col=Operator, log="x", pch=16))

with(qc, plot(GC_hist_bins_75, factor(Machine),
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, factor(FlowCell),
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, factor(Lane),
              col=Operator, pch=16))

with(qc, plot(GC_hist_bins_75, Number_of_unique_15mers,
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, Qual_mean,
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, Qual_median,
              col=Operator, pch=16))


with(qc, plot(GC_hist_bins_75, factor(LibraryPrepPlate),
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, factor(LibraryPrepKitBatch),
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, factor(ClusterKitBatch),
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, factor(SequencingKitBatch),
              col=Operator, pch=16))
with(qc, plot(GC_hist_bins_75, factor(LibraryConcentrationMethod),
              col=Operator, pch=16))



